name: news_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mocktail: ^1.0.4

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.9.3
  test: ^1.25.8
  very_good_analysis: ^7.0.0
