name: news_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  intl: ^0.20.1
  json_annotation: ^4.9.0
  mocktail: ^1.0.4

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3
  test: ^1.25.8
  very_good_analysis: ^7.0.0
